language: python
python:
  - "3.6"

sudo: required

install:
  - make
  - sudo apt-get update && sudo apt-get install oracle-java8-installer

script:
- make test
- make accept

deploy:
  provider: pypi
  user: graknlabs
  password:
    secure: DpxhVpqY9FtSjGUJwPdFWRQf0Ay7Fdf/C2NVgAqQMhDkfNLX1dsdRBS4+xuJY3h349hSmLdxsrFqat1z7C6DBVarDVRSBokG6HIVnqChBOIvYndxeh7Qt/S7r9HCwR2NkChOVa/MaYDaFfyOa77Bsmz4WCOM/Byuq2MjD88U6TFXuKaSaoMjMG7yedQMWajewYNQUVs57UETWsbM1Hi1AOkhvu1lqFjKqRq8OSXpLYc7zH6/vnDOAwJvxCUIh3lPLGmvdqM370vXEvoGTMoPRCuuLH0vL10kR4Qbi1innIsfrfzoTPFgSDMM8cKbTng350RJsGgQTXeRTjgVDfTWNdF4jgVvqLBlqU/0V9fZNp+wrAyniTGc/WTkx5ZqlfjaH9K9yZIyGkF4Pa1NJ6aZCC+/Iv3lBV2wKYXh7M5Z+Pb6SEv+XFYh5WduIHYyV9wm6/o503IvljnXk9qaMjKCSLQf053NN4wHWSILZvnr6NEEqEJ7CRL37G1bFWh/U+j/YUyfQmJP2V8PA/W1iJJviUqvU2KuR9gI89qcmNU7KlFNrKKyjEYH0XA/TXqIBrFhWW3gUnK81sAOXPSB/VD8jOEnnFfSRq/rwkKblyENX2FwQ/Nw0pdPwCtvQt9/8r7o/dB76DAFrBzi1TlpOnJGxap4hOpDl/UjFenseEeQ6ec=
  skip_upload_docs: true